name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install TeXlive
      run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super

    - name: Compile Bid Doc
      run: make -C ./proposal/ all-via-pdf
    - name: Upload Bid pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./github_artifacts

    - name: Compile Planning Doc
      run: make -C ./planning/ all-via-pdf
    - name: Upload Planning pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./github_artifacts
