name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Compile Bid Doc
      run: make -C ./proposal/ all-via-pdf

    - name: Compile Planning Doc
      run: make -C ./planning/ all-via-pdf
